# Generated by Django 2.2.4 on 2019-09-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0002_auto_20190902_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='switchdeck.Place'),
        ),
    ]
