# Generated by Django 2.2.4 on 2019-09-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0003_auto_20190902_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='switchdeck.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game_instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='switchdeck.GameList'),
        ),
    ]
