# Generated by Django 2.2.4 on 2019-09-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0004_auto_20190903_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='prop',
            field=models.CharField(choices=[('k', 'keep'), ('s', 'sell'), ('c', 'change'), ('b', 'buy'), ('w', 'wish')], default='k', max_length=1, verbose_name='Proposition'),
        ),
    ]
