# Generated by Django 2.2.4 on 2019-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0006_auto_20190903_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='prop',
            field=models.CharField(choices=[('k', 'keep'), ('s', 'sell'), ('b', 'buy'), ('w', 'wish')], default='k', max_length=1, verbose_name='Proposition'),
        ),
    ]
