# Generated by Django 3.0.7 on 2020-12-01 21:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date of publication.', verbose_name='Timestamp')),
                ('text', models.TextField(max_length=300, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Set game to can be founded through the global search.', verbose_name='Active')),
                ('desc', models.TextField(blank=True, help_text='Description leaved by the user', max_length=1000, verbose_name='Description')),
                ('prop', models.CharField(choices=[('k', 'keep'), ('s', 'sell'), ('b', 'buy'), ('w', 'wish')], default='k', help_text='Proposition of lot - what user want to do with this game.', max_length=1, verbose_name='Proposition')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount of money user want to buy/sell this game.', max_digits=6, verbose_name='Price')),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of publication. Just additional information.', verbose_name='Public date')),
                ('up_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Up time show last activity from the lot. The newest up time - the highest this lot in lists. Up time update from each comment, updating or etc.', verbose_name='Up time')),
                ('change_to', models.ManyToManyField(blank=True, help_text='List of games user want to change this game.', limit_choices_to=models.Q(('prop', 'b'), ('prop', 'w'), _connector='OR'), related_name='ready_change_to', to='lot.Lot', verbose_name='Change to')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-up_time'],
            },
        ),
    ]
