# Generated by Django 3.0.7 on 2020-12-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='profile',
            field=models.ForeignKey(help_text='Related Profile. Represent the owner of ``Lot`` instance', on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, help_text='Author of the comment.', on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lot',
            field=models.ForeignKey(editable=False, help_text='Related lot.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='lot.Lot', verbose_name='Lot'),
        ),
    ]
