language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"      # current python
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py makemigrations
  - python manage.py collectstatic
# command to run django test
script:
  - python manage.py test
# coverage instruction
after_success:
  - coveralls
