version: '3'

services:
  db:
    image: postgres
    env_file: ./.envs/postgres
    ports: 
      - 55551:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - switchdeck_django
    image: switchdeck_django
    depends_on:
      - db
    env_file:
      - ./.envs/django
      - ./.envs/postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn -w 4 switchdecksite.wsgi --bind="0.0.0.0:8000"

volumes: 
  postgres_data:
