version: '3'

services:
  db:
    image: postgres
    env_file: ./.envs/postgres
    container_name: switchdeck_db
    ports: 
      - 55551:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
      cache_from: 
        - switchdeck_django
    image: switchdeck_django
    container_name: switchdeck_django
    depends_on:
      - db
    env_file:
      - ./.envs/django
      - ./.envs/postgres
    volumes:
      - django_static:/home/switchdeck/static
      - django_media:/home/switchdeck/media
    ports:
      - "8000:8000"
    command: /bin/bash /home/switchdeck/start

volumes: 
  postgres_data:
  django_static:
  django_media:
