version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DATABASE_URL=postgres@db:5432/postgres
      - DEBUG
    command: gunicorn switchdecksite.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
