#!/bin/bash
/bin/python /home/switchdeck/manage.py migrate
# /bin/python3 /home/switchdeck/manage.py compilemessages
/bin/python /home/switchdeck/manage.py collectstatic
/home/switchdeck/.local/bin/gunicorn -w 4 switchdeck.wsgi --bind="0.0.0.0:8000"
