# Generated by Django 3.1.7 on 2021-03-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('catalog_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of page there this game presented in catalog', verbose_name='URL')),
                ('active', models.BooleanField(default=True, help_text='Determine parsing of this link is enabled.', verbose_name='Active')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to='catalog_service.catalog', verbose_name='Catalog')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to='game.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
