# Generated by Django 3.1.7 on 2021-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_catalogs'),
        ('catalog_service', '0002_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'default_related_name': 'links', 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='price_selector',
            field=models.CharField(default='yolo', help_text='CSS selector of object with price num.', max_length=100, verbose_name='Price Selector'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('game', 'catalog')},
        ),
    ]
