# Generated by Django 3.1.7 on 2021-03-07 13:55

from django.db import migrations, models
import django.db.models.deletion
import switchdeck.apps.catalog_service.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0003_auto_20210307_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, help_text='Time of parsing.', verbose_name='Time')),
                ('page_file', models.FileField(help_text='Requested and parsed page.', upload_to=switchdeck.apps.catalog_service.models.upload_to_file_page, verbose_name='Page file')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Parsed price value.', max_digits=6, null=True, verbose_name='Price')),
                ('exception', models.TextField(blank=True, help_text='Text of exception of occured.', null=True, verbose_name='Exception')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_results', related_query_name='parse_result', to='catalog_service.link', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Parse Result',
                'verbose_name_plural': 'Parse Results',
                'ordering': ('time',),
            },
        ),
    ]
