# Generated by Django 3.1.7 on 2021-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0004_parseresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseresult',
            name='exception',
            field=models.TextField(blank=True, help_text='Text of exception if occured.', null=True, verbose_name='Exception'),
        ),
    ]
