# Generated by Django 3.1.7 on 2021-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0005_auto_20210307_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseresult',
            name='successful',
            field=models.BooleanField(default=True, verbose_name='Successful'),
        ),
    ]
