# Generated by Django 3.0.7 on 2020-11-21 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('switchdeck', '0001_initial'),
        ('place', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(help_text='All games user have', related_name='owners', related_query_name='owner', through='switchdeck.Lot', to='switchdeck.Game', verbose_name='Games'),
        ),
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.ForeignKey(default=1, help_text='Place of registration of user. Place of all his lots.', on_delete=django.db.models.deletion.SET_DEFAULT, to='place.Place', verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, help_text='Link to the user instanse, which have authentication methods, email, first name, last name, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
