# Generated by Django 2.2.4 on 2019-11-01 08:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import switchdeck.models


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0008_auto_20190916_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gamelist',
            options={'ordering': ['-up_time'], 'verbose_name': 'GameList', 'verbose_name_plural': 'GameLists'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-popularity', 'name'], 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': ('Profile',), 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, help_text='Author of the comment.', on_delete=django.db.models.deletion.CASCADE, to='switchdeck.Profile', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game_instance',
            field=models.ForeignKey(editable=False, help_text='Related gamelist.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='switchdeck.GameList', verbose_name='GameList'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of publication.', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, help_text='Cover of the game box or any related image.', null=True, upload_to=switchdeck.models.games_images_path, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the game. Related from shop page.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='eshop_url',
            field=models.URLField(blank=True, help_text='Link to page there can locate additional information (nintendo eshop).', null=True, verbose_name='Link to eshop'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='Full name of the game in english (may look from the shop page).', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='active',
            field=models.BooleanField(default=True, help_text='Set game to can be founded through the global search.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='change_to',
            field=models.ManyToManyField(blank=True, help_text='List of games user want to change this game.', limit_choices_to=models.Q(('prop', 'b'), ('prop', 'w'), _connector='OR'), related_name='ready_change_to', to='switchdeck.GameList', verbose_name='Change to'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='desc',
            field=models.TextField(blank=True, help_text='Description leaved by the user', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switchdeck.Game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount of money user want to buy/sell this game.', max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='profile',
            field=models.ForeignKey(help_text='Related Profile. Represent the owner of ``GameList`` instance', on_delete=django.db.models.deletion.CASCADE, to='switchdeck.Profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='prop',
            field=models.CharField(choices=[('k', 'keep'), ('s', 'sell'), ('b', 'buy'), ('w', 'wish')], default='k', help_text='Proposition of gamelist - what user want to do with this game.', max_length=1, verbose_name='Proposition'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='public_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of publication. Just additional information.', verbose_name='Public date'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='up_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Up time show last activity from the gamelist. The newest up time - the highest this gamelist in lists. Up time update from each comment, updating or etc.', verbose_name='Up time'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Name of the region or city.', max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='popularity',
            field=models.IntegerField(default=0, help_text='Popularity of place. The higher popularity - the higher this place in place list.', verbose_name='Popularity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(help_text='All games user have', related_name='owners', related_query_name='owner', through='switchdeck.GameList', to='switchdeck.Game', verbose_name='Games'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.ForeignKey(default=1, help_text='Place of registration of user. Place of all his gamelists.', on_delete=django.db.models.deletion.SET_DEFAULT, to='switchdeck.Place', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, help_text='Link to the user instanse, which have authentication methods, email, first name, last name, etc.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
