# Generated by Django 2.2.8 on 2020-05-04 09:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0009_auto_20191101_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Set game to can be founded through the global search.', verbose_name='Active')),
                ('desc', models.TextField(blank=True, help_text='Description leaved by the user', max_length=1000, verbose_name='Description')),
                ('prop', models.CharField(choices=[('k', 'keep'), ('s', 'sell'), ('b', 'buy'), ('w', 'wish')], default='k', help_text='Proposition of lot - what user want to do with this game.', max_length=1, verbose_name='Proposition')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount of money user want to buy/sell this game.', max_digits=6, verbose_name='Price')),
                ('public_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of publication. Just additional information.', verbose_name='Public date')),
                ('up_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Up time show last activity from the lot. The newest up time - the highest this lot in lists. Up time update from each comment, updating or etc.', verbose_name='Up time')),
                ('change_to', models.ManyToManyField(blank=True, help_text='List of games user want to change this game.', limit_choices_to=models.Q(('prop', 'b'), ('prop', 'w'), _connector='OR'), related_name='ready_change_to', to='switchdeck.Lot', verbose_name='Change to')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switchdeck.Game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-up_time'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='game_instance',
        ),
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(help_text='All games user have', related_name='owners', related_query_name='owner', through='switchdeck.Lot', to='switchdeck.Game', verbose_name='Games'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.ForeignKey(default=1, help_text='Place of registration of user. Place of all his lots.', on_delete=django.db.models.deletion.SET_DEFAULT, to='switchdeck.Place', verbose_name='Place'),
        ),
        migrations.DeleteModel(
            name='GameList',
        ),
        migrations.AddField(
            model_name='lot',
            name='profile',
            field=models.ForeignKey(help_text='Related Profile. Represent the owner of ``Lot`` instance', on_delete=django.db.models.deletion.CASCADE, to='switchdeck.Profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lot',
            field=models.ForeignKey(default=None, editable=False, help_text='Related lot.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='switchdeck.Lot', verbose_name='Lot'),
            preserve_default=False,
        ),
    ]
