# Generated by Django 3.1.7 on 2021-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0002_link'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='catalogs',
            field=models.ManyToManyField(related_name='games', related_query_name='game', through='catalog_service.Link', to='catalog_service.Catalog'),
        ),
    ]
