# Generated by Django 2.2.4 on 2019-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0007_auto_20190916_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['popularity']},
        ),
        migrations.AddField(
            model_name='place',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
