# Generated by Django 3.0.6 on 2020-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchdeck', '0010_auto_20200504_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='slug', max_length=30, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
